### PR TITLE
Makemake Component Request GalleryList #11

### PR DESCRIPTION
**Pull request by ibanzajoe**
Component Request #11 

Feedback requested.

Using variable --color-brand because --color-company no longer available.

### CODE REVIEW

**Comment by drewbaker** [comment]
I just pushed some changes to this PR, I've never done that, curious if they show up for you somewhere?

**Comment by drewbaker** [comment]
Actually, it came out as a new branch. My bad, I got to figure out how to commit back to a PR? Here it is, take a look and study it: https://github.com/funkhaus/factory/tree/pr/14

Let me know if you have any questions. I consider this component done now. I spent 1.5 hours on it.

**Comment by ibanzajoe** [comment]
I feel like you did a complete redo.  I was expecting more comments on how you want it so I can update.  I'll study it and take note of how you want things.

**Comment by drewbaker** [comment]
Yeah I know what you mean, sorry about that, I probably should have done that, there was just so much to it I figure this was probably better. In the future might make more sense to have the first component a dev builds be a simple component, this is certainly on the more complex side.

But I think if you study this you'll learn a lot about our style and expectations.

**Comment by drewbaker** [comment]
@ibanzajoe also here is a slack invite https://join.slack.com/t/component-factory/shared_invite/zt-fafjhq5j-BdPJtDCAZn~BpEydcTubVw

**Pull request merged**
